alter table `character` rename player,
    drop column player_type,

    drop column strength_save_proficiency,
    drop column dexterity_save_proficiency,
    drop column constitution_save_proficiency,
    drop column intelligence_save_proficiency,
    drop column wisdom_save_proficiency,
    drop column charisma_save_proficiency,

    drop column acrobatics_proficiency_bonus,
    drop column animal_handling_proficiency_bonus,
    drop column arcana_proficiency_bonus,
    drop column athletics_proficiency_bonus,
    drop column deception_proficiency_bonus,
    drop column history_proficiency_bonus,
    drop column insight_proficiency_bonus,
    drop column intimidation_proficiency_bonus,
    drop column investigation_proficiency_bonus,
    drop column medicine_proficiency_bonus,
    drop column nature_proficiency_bonus,
    drop column perception_proficiency_bonus,
    drop column performance_proficiency_bonus,
    drop column persuasion_proficiency_bonus,
    drop column religion_proficiency_bonus,
    drop column sleight_of_hand_proficiency_bonus,
    drop column stealth_proficiency_bonus,
    drop column survival_proficiency_bonus,

    add column saves varchar(256) not null default '';